### PR TITLE
Update to kops 1.8.0

### PR DESCRIPTION
**Pull request by mgernand**

### CODE REVIEW

**Comment by FutureSharks** [comment]
Hey thanks for the PR @mgernand !

Have you tested this?

Is the AMI the same? https://github.com/FutureSharks/tf-kops-cluster/blob/master/module/data.tf#L16

Can you also update the version here? https://github.com/FutureSharks/tf-kops-cluster/blob/master/module/variables.tf#L56
And here:
https://github.com/FutureSharks/tf-kops-cluster/blob/master/README.md#versions

**Comment by mgernand** [comment]
> Have you tested this?

The build works from my perspetive, but I'm unable to `kudectl get nodes`. T get "Unable to connect to the server: EOF". I'm seeing the instances of the ELBs as "OutOfService".

> Is the AMI the same? https://github.com/FutureSharks/tf-kops-cluster/blob/master/module/data.tf#L16

The is a new one: `k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02` (from: https://github.com/kubernetes/kops/blob/master/channels/stable). Will change this too.

> Can you also update the version here? https://github.com/FutureSharks/tf-kops-cluster/blob/master/module/variables.tf#L56
And here:
https://github.com/FutureSharks/tf-kops-cluster/blob/master/README.md#versions

Will do.

**Comment by FutureSharks** [comment]
If the master ELB instances are `OutOfService` then it's not working 😀

**Comment by mgernand** [comment]
> If the master ELB instances are OutOfService then it's not working 😀

Will change the missing versions too and check again.

Do I have to change the k8s version here too?,
https://github.com/FutureSharks/tf-kops-cluster/blob/68526855b397782830a9a0feb45b122b55984f6d/module/data/nodeup_node_config.tpl#L6

**Comment by FutureSharks** [comment]
> Do I have to change the k8s version here too?,

Most likely. You need to see what kops wants here and then add it.

**Comment by mgernand** [comment]
The infrastructure is created successfully but the ELBs continue to show "OutOfService". Can you give a hint at what I can look at to fix this?

**Comment by FutureSharks** [comment]
At that point it's lower level kops init stuff.

Does DNS work?
Are the EBS volumes mounted to the masters?
Can the masters resolve each others hostnames?
Can the masters get to internet?

If you log onto a master you can look at the logs `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` to see some more info.

**Comment by mgernand** [comment]
I think Im completely lost right now. 

> Does DNS work?

When running `kudectl cluster-info` I do not get info about the KubeDNS service.

> Are the EBS volumes mounted to the masters?

I can see 10 volumes created (I only created cluster1), but only four of them in-use.:

image

> Can the masters resolve each others hostnames?

Yes, the public and the internal ones.

> Can the masters get to internet?

Yes.

**Comment by FutureSharks** [comment]
FYI `kubectl` won't return anything until a master instance is in-service for the ELB. A master instance won't be in-service until `kube-apiserver` container is running. And `kube-apiserver` won't start until those EBS volumes are mounted.

I'm not 100% what the problem was but it might be tricky to debug here.

I see you've closed the PR and deleted your fork bug I still want to add 1.8 support. I'll add it very soon 🙂

**Comment by mgernand** [comment]
Sorry, I needed to get the cluster running for work. Now I will look further into the kops 1.8.0 upgrade. 

I think I will need to update the hash values in `nodeup_node_config.tpl` right? But where are those values coming from?

**Comment by FutureSharks** [comment]
I've done a large rewrite to support the newer IAM policies and newer versions of k8s/kops:
https://github.com/FutureSharks/tf-kops-cluster/pull/14
I've done a quick test and it looks good. Will test more thoroughly in the new year. Feel free to test it too :)

**Pull request closed without merging**
